- name: Configure macOS
  hosts: localhost
  connection: local
  roles:
    - macos_homebrew
    - macos_config
    - oh_my_zsh
    - role: geerlingguy.mac.dock
      vars:
        # issue
        dockutil_install: false
        dockitems_remove:
          - Launchpad
          - Safari
          - Messages
          - Mail
          - Maps
          - Photos
          - FaceTime
          - Calendar
          - Contacts
          - Reminders
          - Notes
          - Freeform
          - TV
          - Music
          - App Store
          - System Settings
        dockitems_persist:
          - name: iTerm
            path: /Applications/iTerm.app/
          - name: Firefox
            path: /Applications/Firefox.app/
