# most settings changes only take effect on the next login or application restart
- name: Include Dock tasks
  ansible.builtin.include_tasks: dock.yml

- name: Include menu tasks
  ansible.builtin.include_tasks: menu.yml

- name: Include trackpad tasks
  ansible.builtin.include_tasks: trackpad.yml

- name: Include keyboard tasks
  ansible.builtin.include_tasks: keyboard.yml

- name: Configure dark mode
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleInterfaceStyle
    type: string
    value: "{{ macos_config_apple_interface_style }}"

- name: Configure closing windows when quitting an application
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSQuitAlwaysKeepsWindows
    type: boolean
    value: true
