# most settings changes only take effect on the next login or application restart
- name: Include Dock tasks
  ansible.builtin.include_tasks: dock.yml

- name: Include menu tasks
  ansible.builtin.include_tasks: menu.yml

- name: Configure dark mode
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleInterfaceStyle
    type: string
    value: "{{ macos_config_enable_dark_mode }}"
